### ISSUE TITLE
Change blob URL?

### ISSUE THREAD

**Issue by markspolakovs** [rails/activestorage#18]
Is there a way to change the URL of a blob beyond the default `/rails/blobs/<encoded-key>` pattern? It would make it less obvious that it is a Rails app. A config setting like `url_pattern` would be nice.

**Comment by dhh** [comment]
I don't know if it really matters, since this URL pattern is only exposed
in the disk scenario. Which really isn't something you should be using in
production normally. It's intended primarily for testing and development.

Production is intended to be for cloud storage where the URLs generated
will be those for Amazon and Google.

**Comment by dhh** [comment]
Tentatively closing for now, but if you have a use case in mind that I didn't consider, do reopen.
