### ISSUE TITLE
Incompatible with Rails 5.1.2

### ISSUE THREAD

**Issue by teeceepee** [rails/activestorage#39]
In `VerifiedKeyWithExpiration`, `class_attribute` use `default` as an option, which is a new API. `default` option does not appear in activesupport 5.1.2, but there is a line of `s.add_dependency "activesupport", ">= 5.1"` in gemspec.

I think we should add some documents to indicate this incompatibility.

https://github.com/rails/activestorage/blob/master/lib/active_storage/verified_key_with_expiration.rb#L2
https://github.com/rails/rails/pull/29270

**Comment by georgeclaghorn** [comment]
See [the roadmap](https://github.com/rails/activestorage#roadmap).

**Comment by teeceepee** [comment]
I mean you should fix the gemspec to `> 5.1` rather than `>= 5.1`, it's misleading. This is an open repo, anyone who can see it may try to integrate it in their own projects. This incompatibility wasted me several hours, you can just delete one character `=` to eliminate misleading.

**Comment by dhh** [comment]
I've removed that default option. Because in local development with ActiveStorage, I am actually running tests against 5.1. So that shouldn't be a problem.

But yes, as George said, this repo is mainly a staging point for the framework while it's in high flux and prior to getting merged into rails/rails.
